name: lenden
description: "A debt tracking app built with Flutter and Firebase."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'  # More precise SDK constraint

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Dependencies
  firebase_core: ^2.18.0  # Downgraded for stability with other packages
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.15.1
  firebase_storage: ^11.7.1

  # UI & Helpers
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9  # Added for state management (optional but recommended)
  google_sign_in: ^6.1.5    # For Google Auth (optional)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutterfire_cli: ^1.0.0   # For Firebase config management

flutter:
  uses-material-design: true