// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmq-euhckxUizpkp5TmqXWWdpRzSzu6TY',
    appId: '1:296092572812:web:d547aed112124276dfafa9',
    messagingSenderId: '296092572812',
    projectId: 'lenden-app-3d4b4',
    authDomain: 'lenden-app-3d4b4.firebaseapp.com',
    storageBucket: 'lenden-app-3d4b4.firebasestorage.app',
    measurementId: 'G-YNWZFJ25B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApLV2JwBP-ckuhZ3gOOxkk-B-61Ya9fXM',
    appId: '1:296092572812:android:01b1f100af37556edfafa9',
    messagingSenderId: '296092572812',
    projectId: 'lenden-app-3d4b4',
    storageBucket: 'lenden-app-3d4b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8dmcqBCXqtwKi29BwikC6mlo4nIyhU0',
    appId: '1:296092572812:ios:bce256b2012a8973dfafa9',
    messagingSenderId: '296092572812',
    projectId: 'lenden-app-3d4b4',
    storageBucket: 'lenden-app-3d4b4.firebasestorage.app',
    iosBundleId: 'com.example.lenden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8dmcqBCXqtwKi29BwikC6mlo4nIyhU0',
    appId: '1:296092572812:ios:92dd8f39b0c892a7dfafa9',
    messagingSenderId: '296092572812',
    projectId: 'lenden-app-3d4b4',
    storageBucket: 'lenden-app-3d4b4.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmq-euhckxUizpkp5TmqXWWdpRzSzu6TY',
    appId: '1:296092572812:web:c2460d31a23167c0dfafa9',
    messagingSenderId: '296092572812',
    projectId: 'lenden-app-3d4b4',
    authDomain: 'lenden-app-3d4b4.firebaseapp.com',
    storageBucket: 'lenden-app-3d4b4.firebasestorage.app',
    measurementId: 'G-BW33CCBFD4',
  );
}
